### ISSUE TITLE
Get 500 error when calling 'Get quiz list'

### ISSUE THREAD

**Issue by ZengXianhan** [ISSSE31PTDMSSGroup4/msegroups-quiz-service#3]
I run with docker container directly, the docker command is as below:
docker run -dp 5050:5050 -e AWS_ACCESS_KEY_ID='{the key you provided}' -e AWS_SECRET_ACCESS_KEY='{the key you provided}' shajinihubert/msegroups-quiz-service:latest

Then when I tried to call GetQuizList api, it shows the 500 error, and the log in docker shows as follows:

2023-10-16 15:33:44 [2023-10-16 07:33:44,215] ERROR in app: Exception on /api/quiz/list/ [GET]
2023-10-16 15:33:44 Traceback (most recent call last):
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
2023-10-16 15:33:44     response = self.full_dispatch_request()
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023-10-16 15:33:44     rv = self.handle_user_exception(e)
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
2023-10-16 15:33:44     return cors_after_request(app.make_response(f(*args, **kwargs)))
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-10-16 15:33:44     rv = self.dispatch_request()
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
2023-10-16 15:33:44     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-16 15:33:44   File "/app/app/list.py", line 12, in getQuizzesCreatedByUser
2023-10-16 15:33:44     quizzes = dynamodb_handler.getQuizzesByUsername(username)
2023-10-16 15:33:44   File "/app/utils/dynamodb_handler.py", line 23, in getQuizzesByUsername
2023-10-16 15:33:44     response = QuizTable.query(
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 580, in do_action
2023-10-16 15:33:44     response = action(self, *args, **kwargs)
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/boto3/resources/action.py", line 88, in __call__
2023-10-16 15:33:44     response = getattr(parent.meta.client, operation_name)(*args, **params)
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
2023-10-16 15:33:44     return self._make_api_call(operation_name, kwargs)
2023-10-16 15:33:44   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
2023-10-16 15:33:44     raise error_class(parsed_response, operation_name)
2023-10-16 15:33:44 botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the Query operation: The security token included in the request is invalid.
2023-10-16 15:33:44 172.17.0.1 - - [16/Oct/2023 07:33:44] "GET /api/quiz/list/ HTTP/1.1" 500 -

It seems the something wrong with the token, please help to check it out, thank you.

**Comment by shajini0909** [comment]
- could u please download and try with this `quiz.env` file in our gdrive:
`docker run -dp 5050:5050 --env-file C:/Users/Shajini/Downloads/quiz.env shajinihubert/msegroups-quiz-service:latest`

- or, quiz service can now be run from our docker compose -> just need to add the `quiz.env` file

- if still same error.... could you please help to check the values for the following commands in Docker Desktop terminal?
`aws sts get-caller-identity`
`aws configure list`

![image](https://github.com/ISSSE31PTDMSSGroup4/msegroups-quiz-service/assets/121949039/0f1cade7-7554-491d-9a5f-0296fdf665e9)

the creds are still active in my aws, and im able to access it from my local machine, im wondering if it has something to do with other accounts accessing??

**Comment by ZengXianhan** [comment]
I tried on both ways, and both work, thank you
