### ISSUE TITLE
500 Error on CreateQuiz

### ISSUE THREAD

**Issue by ZengXianhan** [ISSSE31PTDMSSGroup4/msegroups-quiz-service#4]
When test Create Quiz api, it shows 500 error, I tried on Postman and frontend and return with the same issue
I post the docker log and the request body as follow to help you to troubleshoot

Request Body:
{
    "title": "My 1st Quiz",
    "questions": [
        {
            "title": "Which gas is essential for respiration?",
            "options": [
                "Oxygen",
                "Nitrogen",
                "Carbon Dioxide",
                "Hydrogen"
            ],
            "answer": "Oxygen",
            "explanation": "Oxygen is crucial for the process of respiration in humans and many other organisms."
        }
    ],
    "remark": "Create Quiz Test"
}

Docker container log:
 [2023-10-17 03:09:10,948] ERROR in app: Exception on /api/quiz/ [POST]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
   File "/app/app/quiz.py", line 24, in createQuiz
     question_id = identifier.genHash(question[keys.INDEX], 4)
KeyError: 'index'
172.19.0.1 - - [17/Oct/2023 03:09:10] "POST /api/quiz/ HTTP/1.1" 500 -

**Comment by ZengXianhan** [comment]
The Get Quiz Detaill API also reports 500 error

The log as follows
 [2023-10-17 11:19:39,413] ERROR in app: Exception on /api/quiz/detail/ [GET]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
   File "/app/app/detail.py", line 14, in getQuizDetail
     quiz = dynamodb_handler.getQuiz(username, quiz_id)
   File "/app/utils/dynamodb_handler.py", line 34, in getQuiz
     return response["Item"]
 KeyError: 'Item'
 172.19.0.1 - - [17/Oct/2023 11:19:39] "GET /api/quiz/detail/?quiz_id=1 HTTP/1.1" 500 -

**Comment by shajini0909** [comment]
For the CreateQuiz API, this is the format that im using on postman:
![image](https://github.com/ISSSE31PTDMSSGroup4/msegroups-quiz-service/assets/121949039/fc5c3dce-1b69-4be4-80a1-6918ab7b2b07)

are we using different versions on postman?
And, do you prefer if we remove "index" from all the methods in the API?

**Comment by shajini0909** [comment]
For Get Quiz Detaill API, i think it's because there is no entry yet. By right, there should be a failure response returned to front-end. I will work on it to do proper exception handling

this error message:
```
return response["Item"]
KeyError: 'Item'
```

means that the value does not exist in the database

**Comment by shajini0909** [comment]
oh! looks like create quiz API worked? I saw a new entry in the database :)

![image](https://github.com/ISSSE31PTDMSSGroup4/msegroups-quiz-service/assets/121949039/a23408f9-5a22-4687-b153-4257537d88c2)

**Comment by ZengXianhan** [comment]
Yes it works, and the get quiz detail also works with the existing record.
I forgot to put 'index' attr of the question when creating new quiz, thanks for indicate that.

I am working on the edit quiz API, will feedback to you later

**Comment by shajini0909** [comment]
I have updated the exception handling for quiz service
